Repository ksauraj/telegram-bash-bot, pull requests merged in 2022-10, with the labels that each got.

#2 Utils: Re-implement methods `--sendaudiofile` & `--sendvoicefile`
  util.sh
Labels: hacktoberfest-accepted

#3 tgbot: spam_protector: Remove overkill blacklist string*
  tgbot.sh
Labels: hacktoberfest-accepted

#5 Add few more spam words
  tgbot.sh
Labels: hacktoberfest-accepted

#6 Utils: Fix up indentation
  util.sh
Labels: enhancement, hacktoberfest-accepted

#7 Let's also use the remaning functions for bot.
  tgbot.sh
Labels: enhancement, help wanted, hacktoberfest-accepted

#8 tgbot: Add Repository Info
  README.md
Labels: enhancement, help wanted, hacktoberfest-accepted

#9 Bot: Add `.round` (Initial)
  .gitignore
  bot/round.sh
  tgbot.sh
Labels: enhancement, help wanted, hacktoberfest-accepted

#11 Bot: Add .shuffle
  .gitignore
  bot/shuffle.sh
  tgbot.sh
Labels: enhancement, hacktoberfest-accepted, feature

#10 Docs : Add better Readme.
  README.md
Labels: documentation, enhancement, help wanted, hacktoberfest-accepted

#13 Implement .shell
  bot/shell.sh
  tgbot.sh
Labels: enhancement, hacktoberfest-accepted, feature

#14 Bot: Add robust checking to .weath
  bot/weath.sh
Labels: enhancement, hacktoberfest-accepted
